console.log("Calcs are running");var questions=14,leadership=[0,0,0,0,0],people=[0,0,0,0,0],systems=[0,0,0,0,0],lead_max=[46,9.2,55.2,92,73.6],peop_max=[23.1,7.7,38.5,77,53.9],syst_max=[8.4,25.2,67.2,84,58.8];function getCheckedValue(b){b=document.getElementsByName(b);for(var a=0;a<b.length;a++)if(b[a].checked)return b[a].value}
function returnScore(){function b(a,b,c){console.log(c+" score is "+a);a[0]=a[0]/b[0]*100;a[1]=a[1]/b[1]*100;a[2]=a[2]/b[2]*100;a[3]=a[3]/b[3]*100;a[4]=a[4]/b[4]*100;console.log(c+" percentages are "+a)}question1answer();question2answer();question3answer();question4answer();question5answer();question6answer();question7answer();question8answer();question9answer();question10answer();question11answer();question12answer();question13answer();question14answer();console.log("Leadership = "+leadership);console.log("People = "+
people);console.log("Systems = "+systems);b(leadership,lead_max,"Leadership");b(people,peop_max,"People");b(systems,syst_max,"Systems");console.log("Sanity check = "+[leadership[0]+leadership[1]+leadership[2]+leadership[3]+leadership[4],people[0]+people[1]+people[2]+people[3]+people[4],systems[0]+systems[1]+systems[2]+systems[3]+systems[4]]);var a=Math.max.apply(null,leadership),c,d=Math.max.apply(null,people),f,e=Math.max.apply(null,systems),g;0===a?(a="You didn't answer any questions yet!",c=""):
leadership[0]===a?(a="Firefighter",c="In Firefighter organisations there are often some reasonable leaders, or leaders with potential. Leaders in these organisations may need to be trained to delegate and manage so that they don't get involved in everything. The leadership team or the whole organisation may be under-resourced, and may need additional help to change the way things are done (i.e. the culture)."):leadership[1]===a?(a="Gambler",c="In Gambler organisations, leadership is either absent or ineffective. 'Gambler' leaders want to be one of the lads as that's where they came from, which doesn't help anyone. Frequently over optimistic about their ability, these leaders avoid being a leader and get involed in their teams jobs, leaving their real tasks until 'tomorrow'. These leaders and the organisation that put them there are 'unconciously incompetent' - in other words the world is a wonderful place and nothing can go wrong. These leaders need to be trained in the basics!"):
leadership[2]===a?(a="Policeman",c="A Policeman organisation leader takes a strong leadership approach; often without providing coaching or guidance, and frequently applying the penalties. These leaders are often called 'old school' and may not have much knowledge or interest in their impact on the workforce. The may demand respect, rather than earning it from their team members, although senior likeminded leaders may praise them for their productivity. Some one on one coaching from a peer is a good way to help this leader improve management of their team."):
leadership[3]===a?(a="President",c="If you're walking down the right path and you're willing to keep walking, eventually you'll make progress."):leadership[4]===a?(a="Stuntman",c="Stuntman organisation's leaders are inspirational; they have presence, they are loved, their people are followers. They appear to be comfortable and calm, and they are tough. With vision and decision the Stuntman leader has the potential to rise to the heights of the organisation. The problem is managing their Achilles heel; they may decide a path for the organisation which is slightly too high risk, and they can fail dramatically. Stuntmen leaders are defined by their 'considered' risk taking and therefore need a trusted team of advisors to guide them away from arrogance or complacency."):
(a="There has been a mistake!",c="Sam, you fool.");0===d?(d="You didn't answer any questions yet!",d=""):people[0]===d?(d="Firefighter",f="The people in a firefighting organisation may be a bit on edge or frustrated, possibly feeling like something is about to happen, or amazed at how the organisation keeps going despite all its problems. Some team building and problem solving shared around can make all the difference."):people[1]===d?(d="Gambler",f="When you ask people if they feel safe they say no. The is an informal approach to work. Sometimes informal teams evolve and work out how to survive, independent of their leader. People wonder what they are doing working for the organisation, realising they may have been conned into their role, so turnover is high as people lose confidence in the leadership team."):
people[2]===d?(d="Policeman",f="The Policeman boss being a stickler for procedure and control may provide some team members with a feeling of security, others may rebel against the prescribed operating style. There is potential for people to do their own thing because they know their leaders are difficult to work with, simply modifying their behaviour when the boss is around. This leads to risk taking, unwritten rules, and often, incidents occurring."):people[3]===d?(d="President",f="If you're walking down the right path and you're willing to keep walking, eventually you'll make progress."):
people[4]===d?(d="Stuntman",f="Stuntman organisations comprise motivated, competent and willing people. If well led a stuntman organisation could overtake others rapidly. Their people are inspired and willing to do high risk work for their leaders, because they know it makes sense for the greater good. Unfortunately despite infections enthusiasm, risk takers operating in a high risk environment often results in a high risk of an incident."):(d="There has been a mistake!",f="Sam, you fool.");0===e?
(e="You didn't answer any questions yet!",e=""):systems[0]===e?(e="Firefighter",g="The systems in a Firefighter organisation are probably not worth the paper they are written on: out of date, not what actually happens, rarely reviewed or audited. A review of how the organisation functions is essential."):systems[1]===e?(e="Gambler",g="This type of organisation downloaded it\u2019s systems from the internet, or obtained them from a mate, changed a few names and left it on the shelf. If there are some systems they are unlikely to be implemented. When asked about his systems, a Gambler leader said - true story - \u201cIt\u2019s all in my head mate, I\u2019ve been doing this for 25 years\u201d..."):
systems[2]===e?(e="Policeman",g="There are probably lots of procedures in a Policeman organisation which were written when things went wrong before. People are expected to comply with them all, possibly leading to a \u2018tick and flick\u2019 (i.e. waste of time) response from the workforce. Some engagement with the workforce to update and roll out the systems will make a positive change."):systems[3]===e?(e="President",g="If you're walking down the right path and you're willing to keep walking, eventually you'll make progress."):
systems[4]===e?(e="Stuntman",g="Stuntman systems may be precise and concise, and may be effective and efficient at controlling risk. The challenge for the systems is their maintenance, as these organisations move so fast that the system can quickly become ineffective, increasing risk."):(e="There has been a mistake!",g="Sam, you fool.");$("#leadership-score").text(a);$("#leadership-blurb").text(c);$("#leadership-image").attr("src","/img/"+a+".png");$("#people-score").text(d);$("#people-blurb").text(f);
$("#people-image").attr("src","/img/"+d+".png");$("#systems-score").text(e);$("#systems-blurb").text(g);$("#systems-image").attr("src","/img/"+e+".png");leadership=[0,0,0,0,0];people=[0,0,0,0,0];systems=[0,0,0,0,0]}function clearResults(){$("#leadership-score").text(" ");$("#leadership-blurb").text(" ");$("#people-score").text(" ");$("#people-blurb").text(" ");$("#systems-score").text(" ");$("#systems-blurb").text(" ");console.log("Results successfully cleared in preparation")}
function question1answer(){"a"===getCheckedValue("question1")?(leadership[0]+=4,people[0]+=.3,systems[0]+=.8):"b"===getCheckedValue("question1")?(leadership[1]+=.8,people[1]+=.1,systems[1]+=2.4):"c"===getCheckedValue("question1")?(leadership[2]+=4.8,people[2]+=.5,systems[2]+=6.4):"d"===getCheckedValue("question1")?(leadership[3]+=8,people[3]+=1,systems[3]+=8):"e"===getCheckedValue("question1")?(leadership[4]+=6.4,people[4]+=.7,systems[4]+=5.6):console.log("Question 1 was not answered!")}
function question2answer(){"a"===getCheckedValue("question2")?(leadership[0]+=5,people[0]+=0,systems[0]+=.4):"b"===getCheckedValue("question2")?(leadership[1]+=1,people[1]+=0,systems[1]+=1.2):"c"===getCheckedValue("question2")?(leadership[2]+=6,people[2]+=0,systems[2]+=3.2):"d"===getCheckedValue("question2")?(leadership[3]+=10,people[3]+=0,systems[3]+=4):"e"===getCheckedValue("question2")?(leadership[4]+=8,people[4]+=0,systems[4]+=2.8):console.log("Question 2 was not answered!")}
function question3answer(){"a"===getCheckedValue("question3")?(leadership[0]+=5,people[0]+=.9,systems[0]+=0):"b"===getCheckedValue("question3")?(leadership[1]+=1,people[1]+=.3,systems[1]+=0):"c"===getCheckedValue("question3")?(leadership[2]+=6,people[2]+=1.5,systems[2]+=0):"d"===getCheckedValue("question3")?(leadership[3]+=10,people[3]+=3,systems[3]+=0):"e"===getCheckedValue("question3")?(leadership[4]+=8,people[4]+=2.1,systems[4]+=0):console.log("Question 3 was not answered!")}
function question4answer(){"a"===getCheckedValue("question4")?(leadership[0]+=3,people[0]+=2.4,systems[0]+=.5):"b"===getCheckedValue("question4")?(leadership[1]+=.6,people[1]+=.8,systems[1]+=1.5):"c"===getCheckedValue("question4")?(leadership[2]+=3.6,people[2]+=4,systems[2]+=4):"d"===getCheckedValue("question4")?(leadership[3]+=6,people[3]+=8,systems[3]+=5):"e"===getCheckedValue("question4")?(leadership[4]+=4.8,people[4]+=5.6,systems[4]+=3.5):console.log("Question 4 was not answered!")}
function question5answer(){"a"===getCheckedValue("question5")?(leadership[0]+=3.5,people[0]+=.6,systems[0]+=1):"b"===getCheckedValue("question5")?(leadership[1]+=.7,people[1]+=.2,systems[1]+=3):"c"===getCheckedValue("question5")?(leadership[2]+=4.2,people[2]+=1,systems[2]+=8):"d"===getCheckedValue("question5")?(leadership[3]+=7,people[3]+=2,systems[3]+=10):"e"===getCheckedValue("question5")?(leadership[4]+=5.6,people[4]+=1.4,systems[4]+=7):console.log("Question 5 was not answered!")}
function question6answer(){"a"===getCheckedValue("question6")?(leadership[0]+=4,people[0]+=1.5,systems[0]+=.5):"b"===getCheckedValue("question6")?(leadership[1]+=.8,people[1]+=.5,systems[1]+=1.5):"c"===getCheckedValue("question6")?(leadership[2]+=4.8,people[2]+=2.5,systems[2]+=4):"d"===getCheckedValue("question6")?(leadership[3]+=8,people[3]+=5,systems[3]+=5):"e"===getCheckedValue("question6")?(leadership[4]+=6.4,people[4]+=3.5,systems[4]+=3.5):console.log("Question 6 was not answered!")}
function question7answer(){var b=[2,.4,2.4,4,3.2],a=[1.2,.4,2,4,2.8],c=[1,3,8,10,7];"a"===getCheckedValue("question7")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question7")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question7")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question7")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question7")?(leadership[4]+=b[4],people[4]+=
a[4],systems[4]+=c[4]):console.log("Question 7 was not answered!")}
function question8answer(){var b=[1,.2,1.2,2,1.6],a=[3,1,5,10,7],c=[.2,.6,1.6,2,1.4];"a"===getCheckedValue("question8")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question8")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question8")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question8")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question8")?(leadership[4]+=b[4],
people[4]+=a[4],systems[4]+=c[4]):console.log("Question 8 was not answered!")}
function question9answer(){var b=[2,.4,2.4,4,3.2],a=[3,1,5,10,7],c=[.2,.6,1.6,2,1.4];"a"===getCheckedValue("question9")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question9")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question9")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question9")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question9")?(leadership[4]+=b[4],
people[4]+=a[4],systems[4]+=c[4]):console.log("Question 9 was not answered!")}
function question10answer(){var b=[2.5,.5,3,5,4],a=[1.5,.5,2.5,5,3.5],c=[.5,1.5,4,5,3.5];"a"===getCheckedValue("question10")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question10")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question10")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question10")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question10")?(leadership[4]+=
b[4],people[4]+=a[4],systems[4]+=c[4]):console.log("Question 10 was not answered!")}
function question11answer(){var b=[2.5,.5,3,5,4],a=[1.5,.5,2.5,5,3.5],c=[1,3,8,10,7];"a"===getCheckedValue("question11")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question11")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question11")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question11")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question11")?(leadership[4]+=
b[4],people[4]+=a[4],systems[4]+=c[4]):console.log("Question 11 was not answered!")}
function question12answer(){var b=[3,.6,3.6,6,4.8],a=[2.7,.9,4.5,9,6.3],c=[.5,1.5,4,5,3.5];"a"===getCheckedValue("question12")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question12")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question12")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question12")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question12")?(leadership[4]+=
b[4],people[4]+=a[4],systems[4]+=c[4]):console.log("Question 12 was not answered!")}
function question13answer(){var b=[5,1,6,10,8],a=[3,1,5,10,7],c=[.8,2.4,6.4,8,5.6];"a"===getCheckedValue("question13")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question13")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question13")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question13")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question13")?(leadership[4]+=b[4],
people[4]+=a[4],systems[4]+=c[4]):console.log("Question 13 was not answered!")}
function question14answer(){var b=[3.5,.7,4.2,7,5.6],a=[1.5,.5,2.5,5,3.5],c=[1,3,8,10,7];"a"===getCheckedValue("question14")?(leadership[0]+=b[0],people[0]+=a[0],systems[0]+=c[0]):"b"===getCheckedValue("question14")?(leadership[1]+=b[1],people[1]+=a[1],systems[1]+=c[1]):"c"===getCheckedValue("question14")?(leadership[2]+=b[2],people[2]+=a[2],systems[2]+=c[2]):"d"===getCheckedValue("question14")?(leadership[3]+=b[3],people[3]+=a[3],systems[3]+=c[3]):"e"===getCheckedValue("question14")?(leadership[4]+=
b[4],people[4]+=a[4],systems[4]+=c[4]):console.log("Question 14 was not answered!")}console.log("Calcs have finished");
